services:
  mongo:
    image: mongo:7.0
    environment:
       ROOT_USERNAME: mongadmin
       ROOT_PASSWORD: admin
    ports:
      - 27017:27017
    volumes:
      - mongodata:/data/db

volumes:
  mongodata:
    driver: local
